-- Insert additional international "Looking for Solutions" opportunities
INSERT INTO opportunities (
  type,
  business_name,
  industry,
  description,
  contact_email,
  contact_phone,
  country,
  city,
  company_size,
  timeline,
  budget_min,
  budget_max,
  currency,
  requirements,
  preferred_contact,
  is_name_private,
  user_id
) VALUES
  (
    'buying',
    'Smart Manufacturing GmbH',
    'Manufacturing',
    'Seeking IoT solution for factory automation and predictive maintenance. Need to monitor 500+ machines in real-time.',
    'tech@smartmanufacturing.de',
    '+49 30 555 0101',
    'Germany',
    'Berlin',
    '501-1000',
    'soon',
    75000,
    150000,
    'EUR',
    'Must integrate with SAP, support Industry 4.0 standards, and provide real-time analytics. German language support required.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'Tokyo Retail Group',
    'Retail',
    'Looking for AI-powered inventory management system with demand forecasting for 200+ stores across Japan.',
    'procurement@tokyoretail.jp',
    '+81 3 5555 0102',
    'Japan',
    'Tokyo',
    '1000+',
    'flexible',
    20000000,
    40000000,
    'JPY',
    'Must support Japanese language, integrate with existing POS systems, and handle multi-store inventory management.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'EcoEnergy Australia',
    'Energy',
    'Need solar panel installation and maintenance service for 50 commercial properties. Looking for turnkey solution.',
    'projects@ecoenergy.com.au',
    '+61 2 5555 0103',
    'Australia',
    'Sydney',
    '201-500',
    'immediate',
    200000,
    400000,
    'AUD',
    'Must be CEC accredited, have commercial installation experience, and provide ongoing maintenance services.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'London Financial Services',
    'Financial Services',
    'Seeking cybersecurity solution for financial compliance and threat detection. FCA compliance required.',
    'security@londonfs.co.uk',
    '+44 20 5555 0104',
    'United Kingdom',
    'London',
    '201-500',
    'immediate',
    50000,
    100000,
    'GBP',
    'Must meet FCA requirements, provide 24/7 monitoring, and integrate with existing security infrastructure.',
    'email',
    true,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'Digital India Tech',
    'Technology',
    'Looking for cloud migration partner to move legacy applications to AWS. Need end-to-end service.',
    'cloud@digitalindia.com',
    '+91 22 5555 0105',
    'India',
    'Mumbai',
    '501-1000',
    'soon',
    2000000,
    5000000,
    'INR',
    'AWS certified partner required. Experience with Java and .NET applications. Local team preferred.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'Singapore Logistics Hub',
    'Transportation',
    'Require warehouse automation system with robotics integration for 50,000 sqft facility.',
    'operations@sglogistics.com',
    '+65 5555 0106',
    'Singapore',
    'Singapore',
    '201-500',
    'flexible',
    100000,
    250000,
    'SGD',
    'Must include AGVs, inventory management system, and warehouse management software.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Insert additional international "Offering Solutions" opportunities
INSERT INTO opportunities (
  type,
  business_name,
  industry,
  description,
  contact_email,
  contact_phone,
  country,
  city,
  company_size,
  timeline,
  budget_min,
  budget_max,
  currency,
  requirements,
  preferred_contact,
  is_name_private,
  user_id
) VALUES
  (
    'selling',
    'IndustrieAutomation GmbH',
    'Manufacturing',
    'Complete Industry 4.0 solution with IoT sensors, predictive maintenance, and real-time monitoring. Used by leading manufacturers.',
    'sales@industrieautomation.de',
    '+49 89 555 0201',
    'Germany',
    'Munich',
    '201-500',
    'immediate',
    null,
    null,
    'EUR',
    'Certified SAP partner. Multi-language support. Full implementation and training included.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'AI Retail Solutions Japan',
    'Technology',
    'AI-powered retail management platform with inventory optimization, demand forecasting, and automated ordering.',
    'sales@airetail.jp',
    '+81 3 5555 0202',
    'Japan',
    'Tokyo',
    '51-200',
    'flexible',
    null,
    null,
    'JPY',
    'Supports all major Japanese POS systems. Proven 30% inventory cost reduction.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'GreenPower Solutions',
    'Energy',
    'Commercial solar installation and maintenance services. Over 1000 successful installations across Australia.',
    'sales@greenpower.com.au',
    '+61 2 5555 0203',
    'Australia',
    'Sydney',
    '201-500',
    'immediate',
    null,
    null,
    'AUD',
    'CEC accredited. 25-year warranty. Comprehensive maintenance plans available.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'CyberSecure UK',
    'Technology',
    'FCA-compliant cybersecurity solution with AI threat detection, compliance monitoring, and incident response.',
    'enterprise@cybersecure.co.uk',
    '+44 20 5555 0204',
    'United Kingdom',
    'London',
    '201-500',
    'immediate',
    null,
    null,
    'GBP',
    'FCA and GDPR compliant. Used by top UK financial institutions. 24/7 SOC included.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'CloudTech India',
    'Technology',
    'Expert AWS migration services with zero-downtime transition. Comprehensive cloud architecture and optimization.',
    'migrate@cloudtech.in',
    '+91 80 5555 0205',
    'India',
    'Bangalore',
    '501-1000',
    'flexible',
    null,
    null,
    'INR',
    'AWS Advanced Partner. 100+ successful migrations. Local support teams available.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'RoboWarehouse Systems',
    'Technology',
    'Complete warehouse automation solution with custom robotics integration and intelligent management software.',
    'solutions@robowarehouse.sg',
    '+65 5555 0206',
    'Singapore',
    'Singapore',
    '201-500',
    'immediate',
    null,
    null,
    'SGD',
    'Turnkey automation solution. 50+ successful deployments in APAC. 24/7 support.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  );