-- Clear existing opportunities first
DELETE FROM opportunities;

-- Insert sample "Looking for Solutions" opportunities
INSERT INTO opportunities (
  type,
  business_name,
  industry,
  description,
  contact_email,
  contact_phone,
  country,
  city,
  company_size,
  timeline,
  budget_min,
  budget_max,
  currency,
  requirements,
  preferred_contact,
  is_name_private,
  user_id
) VALUES
  (
    'buying',
    'TechFlow Solutions',
    'Technology',
    'Looking for a modern SaaS platform to manage our customer support operations. Need ticketing, knowledge base, and chat integration capabilities.',
    'procurement@techflow.com',
    '(415) 555-0101',
    'United States',
    'San Francisco',
    '51-200',
    'soon',
    15000,
    30000,
    'USD',
    'Must have: API integration, SSO support, compliance certifications. Experience with tech companies preferred.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'Global Retail Corp',
    'Retail',
    'Seeking enterprise CRM solution to manage 100k+ customer relationships. Must integrate with our existing e-commerce platform.',
    'it@globalretail.com',
    '(212) 555-0102',
    'United States',
    'New York',
    '1000+',
    'immediate',
    50000,
    100000,
    'USD',
    'Enterprise-grade CRM with e-commerce integration, analytics, and mobile support. Must handle high volume.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'FastTrack Logistics',
    'Transportation',
    'Need comprehensive fuel card solution for our fleet of 200+ trucks. Looking for competitive rates and real-time tracking.',
    'fleet@fasttrack.com',
    '(312) 555-0103',
    'United States',
    'Chicago',
    '201-500',
    'immediate',
    null,
    null,
    'USD',
    'National coverage, fraud protection, detailed reporting, and driver app integration required.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'Metropolitan Services',
    'Professional Services',
    'Seeking professional cleaning service provider for our 5 office locations. Daily cleaning required with occasional deep cleaning.',
    'facilities@metroserv.com',
    '(617) 555-0104',
    'United States',
    'Boston',
    '501-1000',
    'flexible',
    75000,
    120000,
    'USD',
    'Must be licensed and insured. Green cleaning products preferred. Experience with corporate offices required.',
    'email',
    true,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'buying',
    'HealthCare Plus',
    'Healthcare',
    'Looking for HIPAA-compliant patient management software. Must handle scheduling, billing, and electronic health records.',
    'tech@healthcareplus.com',
    '(305) 555-0105',
    'United States',
    'Miami',
    '51-200',
    'soon',
    40000,
    80000,
    'USD',
    'HIPAA compliance mandatory. Cloud-based solution preferred. Must integrate with major insurance providers.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  );

-- Insert sample "Offering Solutions" opportunities
INSERT INTO opportunities (
  type,
  business_name,
  industry,
  description,
  contact_email,
  contact_phone,
  country,
  city,
  company_size,
  timeline,
  budget_min,
  budget_max,
  currency,
  requirements,
  preferred_contact,
  is_name_private,
  user_id
) VALUES
  (
    'selling',
    'SupportHub Solutions',
    'Technology',
    'Leading customer support platform with AI-powered ticketing, knowledge base, and omnichannel support. Used by 1000+ companies.',
    'sales@supporthub.com',
    '(408) 555-0201',
    'United States',
    'San Jose',
    '51-200',
    'immediate',
    null,
    null,
    'USD',
    'Perfect for medium to large enterprises. Quick implementation. 24/7 support included.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'Enterprise CRM Pro',
    'Technology',
    'Enterprise-grade CRM solution with advanced analytics, automation, and seamless e-commerce integration. 99.9% uptime guaranteed.',
    'enterprise@crmpro.com',
    '(650) 555-0202',
    'United States',
    'San Francisco',
    '201-500',
    'flexible',
    null,
    null,
    'USD',
    'Scalable solution for large enterprises. Full migration support and training included.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'FleetCard Solutions',
    'Financial Services',
    'Comprehensive fuel card program with nationwide coverage. Real-time tracking, fraud protection, and competitive rates.',
    'sales@fleetcard.com',
    '(214) 555-0203',
    'United States',
    'Dallas',
    '201-500',
    'immediate',
    null,
    null,
    'USD',
    'Ideal for fleets of all sizes. Mobile app and 24/7 support included. Volume discounts available.',
    'phone',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'CleanPro Services',
    'Professional Services',
    'Commercial cleaning services with 15 years of experience. Eco-friendly products, trained staff, and flexible scheduling.',
    'contracts@cleanpro.com',
    '(202) 555-0204',
    'United States',
    'Washington DC',
    '201-500',
    'immediate',
    null,
    null,
    'USD',
    'Licensed and insured. Green cleaning certified. Corporate office experience. Custom cleaning plans.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  ),
  (
    'selling',
    'MedTech Solutions',
    'Healthcare',
    'Complete healthcare management platform. HIPAA-compliant, cloud-based, with integrated EHR, billing, and scheduling.',
    'sales@medtechsolutions.com',
    '(617) 555-0205',
    'United States',
    'Boston',
    '51-200',
    'flexible',
    null,
    null,
    'USD',
    'Fully HIPAA compliant. Used by 500+ healthcare providers. Full training and support included.',
    'email',
    false,
    (SELECT id FROM auth.users LIMIT 1)
  );